version: '3.8'
services:
  db:
    container_name: db
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_DB: "ads"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
#      PGDATA: /var/lib/postgresql/data/db_data_ads/
    volumes:
#      - .:/docker-entrypoint-initdb.d
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data_ads:/var/lib/postgresql/data
    ports:
      - 5433:5433
  ads:
#    build: ./Dockerfile
    build: .
#    image: ads
#    links:
#      - "postgres"
    depends_on:
      - db
    container_name: ads
    ports:
      - 9092:9092
    restart: always
    environment:
      PGHOSTAllPATH: db
      DB_HOST: localhost
      DB_NAME: ads
      DB_POST: 5437
      DB_USERNAME: "postgres"
      DB_PASSWORD: "admin"
      SWAGGER_ADDRESS: localhost
      SERVER_PORT: 9092

volumes:
  db_data_ads: